### PR TITLE
updated register page and added option for log in

### PR DESCRIPTION
**Pull request by faith-ima**
cleaned up the registration page and added an option for the user to be directed to the login page(needs backend connection). Should I remove the section with the coupon and the "get in touch"? The latter can be changed to info pertaining to electric bluefish productions

### CODE REVIEW

**Review by fayloads — CHANGES_REQUESTED** [review]
This looks great @faith-ima ! I woud take out the coupon and contact us blocks. To replace the "contact us", I will be adding our issue collector to all of our pages.

**Comment by faith-ima** [comment]
All done. Don't have privilege to access the issue collector on jira but we should be able to do this in the future

**Comment by fayloads** [comment]
> All done. Don't have privilege to access the issue collector on jira but we should be able to do this in the future

I will handle this :)

**Review by fayloads — APPROVED** [review]
Great work @faith-ima 🥳

**Pull request merged**
