### PR TITLE
login page adjusted. Added register link, redirecting to register page

### PR DESCRIPTION
**Pull request by Necosama**

### CODE REVIEW

**Comment by fayloads** [comment]
@Necosama Why did we delete the controllers and the kernel code? 
I am not able to access the login page. I am getting an error in runtime.

**Comment by Necosama** [comment]
I'm not sure why this time Github just deleted those files. Last time, it just remove the changes between the local repo and remote. But now, I added those three files back: 
Kernel.php under app/Http,
Login.php under app/Http/Controller/Auth, 
and IndexController.php under app/Http/Controller.
Please review them again. Thank you for letting me know.

**Review by fayloads — CHANGES_REQUESTED** [review]
Great work adding the files back in and the register here button!! 
I am struggling to be directed to the registration page. There seems to be no behavior when clicking the registration button. Please see the recording.
https://user-images.githubusercontent.com/73084642/159273102-d7c423d5-2840-4def-952f-248f74deda1b.mov

**Comment by YouCopy** [comment]
Looked it over, and there seems to be no functionality added to the registration link. I was assuming that the registration would be pulled down in like a drop-down menu after hitting the button? Do you want the backend to redirect to the registration page? No idea of what the bigger picture here is.

**Comment by Necosama** [comment]
I just added the action. It will redirect to the Register page when the user clicked the "register".  I'm not sure if Faith already made the register page, if so, I guess after merging everything together, the whole process will go smoothly.

**Comment by fayloads** [comment]
@Necosama Can you please bring this branch up to date with the main branch?

**Review by fayloads — APPROVED** [review]

**Pull request merged**
