### PR TITLE
Git checkout  b an 50 create login page

### PR DESCRIPTION
**Pull request by faith-ima**
This branch contains both the html and css code required to create the user login page, together with the app icon. To run run the code, the repo should be cloned and opened through vscode or any preferred ide, checkout to this branch, navigate to the frontend folder and run the file "createLoginPage", it should request access to chrome.

### CODE REVIEW

**Comment by fayloads** [comment]
@faith-ima would you provide a description stating what this is and with steps for how to run the code? 
Great work!

**Review by fayloads — CHANGES_REQUESTED** [review]
@faith-ima Great work on creating a login page and adding the PR description with steps to reproduce. Would you please move the HTML into `project-anemone/resources/views` directory? You can see an example in [Wenkai's html migration](https://github.com/Capstone-Projects-2022-Spring/project-anemone/pull/4/files)

**Comment by faith-ima** [comment]
files have been moved to project-anemone/resources/views

**Comment by avariantphi** [comment]
@faith-ima Great work! Have you and @ChenxuanSun123 and @Necosama decided which login page we will be using?

**Review by fayloads — CHANGES_REQUESTED** [review]
@faith-ima Great work! Have you and @ChenxuanSun123 and @Necosama decided which login page we will be using?

I also think we can remove the vscode configuration. Or, perhaps add the directory to our `.gitignore`

**Comment by faith-ima** [comment]
I believe @ChenxuanSun123 and @Necosama are working on the registration/sign up page, I'm not sure

**Comment by fayloads** [comment]
> I believe @ChenxuanSun123 and @Necosama are working on the registration/sign up page, I'm not sure

Okay cool! great work!! 
@YouCopy @Necosama @ChenxuanSun123 Would you all please review Faith's awesome work? Let's have a collective approval :)

**Comment by fayloads** [comment]
This work has been moved into https://github.com/Capstone-Projects-2022-Spring/project-anemone/pull/6

**Pull request closed without merging**
