### PR TITLE
AN-42 Create DB and create User table

### PR DESCRIPTION
**Pull request by fayloads**
Typically, PRs encapsulate small changes. PRs are typically 6 files or less. Given the Laravel skeleton, this PR is an exception.

**The point of this pull request was to create a database source and the User table.**
*The effort is contained within the Laravel skeleton since the database source is created via script within the Laravel project.*

The next steps are to be able to test retrieve user information and request user registration.

### CODE REVIEW

**Comment by YouCopy** [comment]
Compared it to the skeleton that my Laravel installation gave me, and it looks like nothing superfluous was added, and it seems like the .gitignore file did it's job well

**Review by YouCopy — COMMENTED** [review]
Ignore this, wrote a comment instead of approving

**Review by YouCopy — APPROVED** [review]
Compared it to the skeleton that my Laravel installation gave me, and it looks like nothing superfluous was added, and it seems like the .gitignore file did it's job well

**Comment by fayloads** [comment]
To reproduce:
First follow appropriate steps for your OS from https://laravel.com/docs/master/installation
Then to set up the db run the following from your `mysql` docker container (access the command line via the docker dashboard)
to connect to db run `mysql -u root -p -h localhost`
and then in the cli run `show databases;`
you will see our db.
i suggest opening the cli from docker dashboard for mysql component
then run `use project_anemone;`
run `show tables;`
you should see `users`

**Pull request merged**
