### PR TITLE
An 80 create email verification page

### PR DESCRIPTION
**Pull request by faith-ima**
added email verification page that tells the user to go to their email to verify their account and includes an option to resend the email notification. To test page go to emailverify.html, right click, select copy path and paste in browser to view.

### CODE REVIEW

**Comment by fayloads** [comment]
Screen Shot 2022-03-23 at 6 17 32 PM
@faith-ima I am seeing the old registration page on this branch. Did you relay your changes on top of main? Or, bring main into your branch?

**Comment by faith-ima** [comment]
The branch for the verification page was pulled from main before the new registration page was merged

**Comment by faith-ima** [comment]
I did a rebase. It should be showing the new page now. Please let me know if it works

**Comment by fayloads** [comment]
@faith-ima I am not able to get to the new page. I see it in the views, when I access `*/email/verify` I am still viewing the old layout.
Screen Shot 2022-03-24 at 3 54 16 PM
When I click the verify my email link in the email
Screen Shot 2022-03-24 at 3 58 16 PM
 I am still redirected to index still.
Screen Shot 2022-03-24 at 3 57 55 PM

**Review by fayloads — APPROVED** [review]
Screen Shot 2022-03-24 at 5 13 22 PM
LGTM! Great job @faith-ima

**Pull request merged**
