### PR TITLE
An 63 arrange resources of front end

### PR DESCRIPTION
**Pull request by Necosama**
Array the files under folder front into folder resources.

### CODE REVIEW

**Review by fayloads — CHANGES_REQUESTED** [review]
Great work on moving the html into their respectable location! 🎉  
please move all CSS files into `project-anemone/resources/css/` directory

**Review by fayloads — CHANGES_REQUESTED** [review]
Great work on moving all the files into the `*/css` directory!! 
Can you help me understand what the purpose is for the `*/front` directory and all files within?
If we do not need them, please remove all files that are not within our `project-anemone` directory.

**Comment by Necosama** [comment]
Got it. Actually, we don't really need them anymore. I will try to remove it.
________________________________
发件人: Fay ***@***.***>
发送时间: 2022年3月8日 14:42
收件人: Capstone-Projects-2022-Spring/project-anemone ***@***.***>
抄送: Wenkai Zhai ***@***.***>; Author ***@***.***>
主题: [External] Re: [Capstone-Projects-2022-Spring/project-anemone] An 63 arrange resources of front end (PR #4)


@avariantphi requested changes on this pull request.

Great work on moving all the files into the */css directory!!
Can you help me understand what the purpose is for the */front directory and all files within?
If we do not need them, please remove all files that are not within our project-anemone directory.

―
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCapstone-Projects-2022-Spring%2Fproject-anemone%2Fpull%2F4%23pullrequestreview-903497083&data=04%7C01%7Cwenkaizhai%40temple.edu%7C9a93c0d2110346fee52808da013bd164%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637823653709124461%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tYR5fUa7nRUjEX%2FLA6aIeXCUhfsbOroXtX4lVFyrB%2Fo%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQYEQJQQFRSPLRA55I7BQ7LU66UTLANCNFSM5PPKC2NA&data=04%7C01%7Cwenkaizhai%40temple.edu%7C9a93c0d2110346fee52808da013bd164%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637823653709124461%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FxhS4J91b%2BdBlRprtJ3DGK8aaz6y4DowplaYbZSxZ5Q%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cwenkaizhai%40temple.edu%7C9a93c0d2110346fee52808da013bd164%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637823653709124461%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cNBVT7yYX%2BhGkOMV9dnXjWN73I2QG99uGvaj20HsDJo%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cwenkaizhai%40temple.edu%7C9a93c0d2110346fee52808da013bd164%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637823653709124461%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xEzXTKHuJBLWKaUpdcyTPNsieUAfzvRDD8DYi2rRtI4%3D&reserved=0>.

**Comment by fayloads** [comment]
> Got it. Actually, we don't really need them anymore. I will try to remove it.
> […](#)
> ________________________________ 发件人: Fay ***@***.***> 发送时间: 2022年3月8日 14:42 收件人: Capstone-Projects-2022-Spring/project-anemone ***@***.***> 抄送: Wenkai Zhai ***@***.***>; Author ***@***.***> 主题: [External] Re: [Capstone-Projects-2022-Spring/project-anemone] An 63 arrange resources of front end (PR #4) @avariantphi requested changes on this pull request. Great work on moving all the files into the */css directory!! Can you help me understand what the purpose is for the */front directory and all files within? If we do not need them, please remove all files that are not within our project-anemone directory. ― Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCapstone-Projects-2022-Spring%2Fproject-anemone%2Fpull%2F4%23pullrequestreview-903497083&data=04%7C01%7Cwenkaizhai%40temple.edu%7C9a93c0d2110346fee52808da013bd164%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637823653709124461%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tYR5fUa7nRUjEX%2FLA6aIeXCUhfsbOroXtX4lVFyrB%2Fo%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQYEQJQQFRSPLRA55I7BQ7LU66UTLANCNFSM5PPKC2NA&data=04%7C01%7Cwenkaizhai%40temple.edu%7C9a93c0d2110346fee52808da013bd164%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637823653709124461%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FxhS4J91b%2BdBlRprtJ3DGK8aaz6y4DowplaYbZSxZ5Q%3D&reserved=0>. Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cwenkaizhai%40temple.edu%7C9a93c0d2110346fee52808da013bd164%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637823653709124461%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cNBVT7yYX%2BhGkOMV9dnXjWN73I2QG99uGvaj20HsDJo%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cwenkaizhai%40temple.edu%7C9a93c0d2110346fee52808da013bd164%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C637823653709124461%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xEzXTKHuJBLWKaUpdcyTPNsieUAfzvRDD8DYi2rRtI4%3D&reserved=0>. You are receiving this because you authored the thread.Message ID: ***@***.***>

Awesomesauce! lmk when you are ready for another review :)

**Comment by fayloads** [comment]
This work has been moved into https://github.com/Capstone-Projects-2022-Spring/project-anemone/pull/6

**Pull request closed without merging**
