### PR TITLE
Changed verification page to Faith's and removed the old version

### PR DESCRIPTION
**Pull request by YouCopy**
At the moment, it looks like some css stuff is still broken on the page. I also had to remove the old "Resend Email" button because I need the route to be posted and not gotten. Basically, I needed to remove the href tag and replace it with  the only thing I knew that would work. Someone needs to spend the time to fix the css and make sure that the button looks better than what I had to improvise with.

I briefly tested registration, login, and logout, and everything seems to be working properly there. Just changed the link in the registration page to go directly to login.

Also, not entirely sure what all the weird zone identifier stuff is all about, but it may be related the the css problem? If someone wants to explain that to me, that'd be ideal.

### CODE REVIEW

**Comment by fayloads** [comment]
@YouCopy Looks like `Zone.Identifier` when moving, copy/paste files into WSL filespace. 
A hackey workaround executing `cd ~ && find . -name "*:Zone.Identifier" -type f -delete` may suffice.
Also, everyone should make sure their file explorers are set to show hidden files.


I will add to our `.gitignore` the unwarranted extension (I will be updating the repo hierarchy soon).

**Comment by fayloads** [comment]
It also looks like Windows and WSL users can access their Group Policy configurations and enable `Do not preserve zone information in file attachments`

**Review by fayloads — CHANGES_REQUESTED** [review]
You need to point the right directory. Crawling up one level should help. 
```
<td bgcolor="#ffffff" align="center" valign="top"
    style="padding: 40px 20px 20px 20px; border-radius: 4px 4px 0px 0px; color: #111111; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 48px; font-weight: 400; letter-spacing: 4px; line-height: 48px;">
    <h1 style="font-size: 48px; font-weight: 400; margin: 2;">Welcome!</h1>
    <img align="center" width="100%" height="100%" src="../anemone.png" />
</td>
```
Screen Shot 2022-03-29 at 10 39 28 AM

**Comment by fayloads** [comment]
@YouCopy Please update this with main to avoid merge conflicts

**Comment by fayloads** [comment]
@YouCopy I can't get the app to work in the browser. @faith-ima Are you able to pull down the changes and test?

**Review by faith-ima — APPROVED** [review]
Looks great!

**Pull request merged**
